import type { WorkspaceSnapshot } from "./types";

const categoryNames = [
  "Venue",
  "Catering",
  "Decoration",
  "Photography",
  "Bride",
  "Groom",
  "Jewellery",
  "Rituals",
  "Invitations",
  "Transport",
  "Accommodation",
  "Gifts",
  "Hidden Expenses",
  "Miscellaneous",
];

export const demoWorkspace: WorkspaceSnapshot = {
  version: 2,
  wedding: {
    id: "wedding-1",
    name: "Suman & Sumita",
    type: "Odia Hindu Wedding",
    date: "2026-12-14",
    location: "Berhampur, Odisha",
    currency: "INR",
    guestEstimate: 800,
    budgetTargetPaise: 280000000,
  },
  events: [
    {
      id: "event-engagement",
      name: "Engagement",
      date: "2026-12-10",
      time: "18:30",
      endTime: "21:00",
      location: "Berhampur, Odisha",
      notes: "Ring ceremony and family dinner.",
      colorToken: "gold",
      iconKey: "rings",
      requiredItems: [],
      sortOrder: 0,
    },
    {
      id: "event-haldi",
      name: "Haldi",
      date: "2026-12-12",
      time: "09:00",
      endTime: "11:00",
      location: "Family home",
      notes: "Keep turmeric and floral jewellery ready.",
      colorToken: "gold",
      iconKey: "sparkles",
      requiredItems: [],
      sortOrder: 1,
    },
    {
      id: "event-mehendi",
      name: "Mehendi",
      date: "2026-12-12",
      time: "17:00",
      endTime: "21:00",
      location: "Family home",
      notes: "Green and gold theme. Welcome drinks and light snacks.",
      colorToken: "botanical",
      iconKey: "hand",
      requiredItems: [
        { id: "required-decor", label: "Decor items", completed: 12, total: 16 },
        { id: "required-mehendi", label: "Mehendi items", completed: 5, total: 6 },
        { id: "required-gifts", label: "Return gifts", completed: 8, total: 10 },
      ],
      sortOrder: 2,
    },
    {
      id: "event-wedding",
      name: "Wedding",
      date: "2026-12-14",
      time: "19:00",
      endTime: "23:30",
      location: "Berhampur, Odisha",
      notes: "Ceremonies and customs remain editable for the family.",
      colorToken: "terracotta",
      iconKey: "mandap",
      requiredItems: [{ id: "required-ceremony", label: "Ceremony items", completed: 6, total: 8 }],
      sortOrder: 3,
    },
    {
      id: "event-reception",
      name: "Reception",
      date: "2026-12-15",
      time: "19:00",
      endTime: "22:30",
      location: "Berhampur, Odisha",
      colorToken: "sage",
      iconKey: "music",
      requiredItems: [],
      sortOrder: 4,
    },
    {
      id: "event-gruhapravesh",
      name: "Gruhapravesh",
      date: "2026-12-16",
      time: "10:00",
      location: "Family home",
      colorToken: "botanical",
      iconKey: "home",
      requiredItems: [],
      sortOrder: 5,
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Confirm catering menu",
      description: "Finalize the menu, service plan, and dietary notes.",
      category: "Food & catering",
      eventId: "event-wedding",
      dueDate: "2026-10-20",
      priority: "High",
      status: "In Progress",
      responsiblePerson: "Suman",
      checklist: [
        { id: "task-1-check-1", title: "Review tasting notes", completed: true },
        { id: "task-1-check-2", title: "Confirm final guest count", completed: false },
      ],
      attachments: [],
    },
    {
      id: "task-2",
      title: "Collect invitation proof",
      category: "Invitations",
      eventId: "event-engagement",
      dueDate: "2026-10-10",
      priority: "Medium",
      status: "Not Started",
      responsiblePerson: "Sumita",
      checklist: [],
      attachments: [],
    },
    {
      id: "task-3",
      title: "Book bridal mehendi artist",
      category: "Artists",
      eventId: "event-mehendi",
      dueDate: "2026-09-30",
      priority: "High",
      status: "Completed",
      responsiblePerson: "Sumita",
      checklist: [],
      attachments: [],
    },
    {
      id: "task-4",
      title: "Confirm the final family transport and accommodation pickup schedule",
      category: "Transport",
      eventId: "event-wedding",
      dueDate: "2026-07-05",
      priority: "Critical",
      status: "In Progress",
      responsiblePerson: "Suman",
      notes: "Confirm vehicle count before the next planning call.",
      checklist: [],
      attachments: [],
    },
  ],
  categories: categoryNames.map((name, sortOrder) => ({
    id: `category-${sortOrder + 1}`,
    name,
    sortOrder,
  })),
  expenses: [
    {
      id: "expense-1",
      title: "Wedding venue advance",
      categoryId: "category-1",
      estimatedPaise: 350000000,
      actualPaise: 360000000,
      paidPaise: 100000000,
      paymentStatus: "Partially Paid",
      date: "2026-07-01",
      eventId: "event-wedding",
      vendorName: "Berhampur Convention Hall",
      dueDate: "2026-11-14",
    },
    {
      id: "expense-2",
      title: "Photography booking",
      categoryId: "category-4",
      estimatedPaise: 150000000,
      actualPaise: 150000000,
      paidPaise: 150000000,
      paymentStatus: "Paid",
      date: "2026-06-20",
      eventId: "event-wedding",
      vendorName: "Frame Story Studios",
    },
    {
      id: "expense-3",
      title: "Catering estimate",
      categoryId: "category-2",
      estimatedPaise: 450000000,
      actualPaise: 0,
      paidPaise: 0,
      paymentStatus: "Not Paid",
      date: "2026-07-05",
      eventId: "event-wedding",
      vendorName: "Annapurna Caterers",
      dueDate: "2026-12-07",
    },
    {
      id: "expense-4",
      title: "Reception stage, floral installation and lighting package",
      categoryId: "category-3",
      estimatedPaise: 160000000,
      actualPaise: 185000000,
      paidPaise: 60000000,
      paymentStatus: "Partially Paid",
      date: "2026-07-08",
      eventId: "event-reception",
      vendorName: "Saanvi Event Decor",
      dueDate: "2026-09-08",
      notes: "Final flower selection is pending family approval.",
    },
  ],
  households: [
    {
      id: "household-1",
      name: "Patnaik Family",
      side: "partnerOne",
      guestCount: 3,
      invitationStatus: "Delivered",
      accommodationStatus: "Booked",
      transportStatus: "Booked",
      guests: [
        { id: "guest-1", name: "Rajesh Patnaik", rsvpStatus: "Confirmed" },
        { id: "guest-2", name: "Priyadarshini Patnaik", rsvpStatus: "Confirmed" },
        { id: "guest-3", name: "Ananya Patnaik", rsvpStatus: "Pending" },
      ],
    },
    {
      id: "household-2",
      name: "Mishra Family",
      side: "partnerTwo",
      guestCount: 2,
      invitationStatus: "Sent",
      accommodationStatus: "Needed",
      transportStatus: "Not Needed",
      guests: [
        { id: "guest-4", name: "Arun Mishra", rsvpStatus: "Confirmed" },
        { id: "guest-5", name: "Maya Mishra", rsvpStatus: "Confirmed" },
      ],
    },
    {
      id: "household-3",
      name: "Friends Group",
      side: "both",
      guestCount: 2,
      invitationStatus: "Sent",
      accommodationStatus: "Not Needed",
      transportStatus: "Needed",
      guests: [
        { id: "guest-6", name: "Aarav Sahu", rsvpStatus: "Pending" },
        { id: "guest-7", name: "Diya Behera", rsvpStatus: "Declined" },
      ],
    },
  ],
  gifts: [
    {
      id: "gift-1",
      kind: "Received",
      personName: "Rajesh & Priyadarshini Patnaik",
      relationship: "Family",
      itemName: "Silver dinner set",
      valuePaise: 2400000,
      valueIsEstimated: true,
      date: "2026-12-10",
      thankedStatus: "Done",
      thankedDate: "2026-12-11",
      returnGiftStatus: "Done",
      returnGiftDate: "2026-12-10",
    },
    {
      id: "gift-2",
      kind: "Received",
      personName: "Sushant Kumar Sahu",
      relationship: "Cousin",
      itemName: "Cash",
      valuePaise: 1100000,
      date: "2026-12-14",
      thankedStatus: "Done",
      thankedDate: "2026-12-15",
      returnGiftStatus: "Done",
      returnGiftDate: "2026-12-14",
    },
    {
      id: "gift-3",
      kind: "Given",
      personName: "Family elders",
      itemName: "Ceremonial gifts",
      valuePaise: 5100000,
      valueIsEstimated: true,
      date: "2026-12-14",
      thankedStatus: "Pending",
      returnGiftStatus: "Pending",
    },
  ],
  emergencyContacts: [
    {
      id: "contact-1",
      name: "Rajat Maharana",
      role: "Family coordinator",
      phone: "+919876543210",
      iconKey: "users",
    },
    {
      id: "contact-2",
      name: "Venue desk",
      role: "Venue manager",
      phone: "+911412385700",
      iconKey: "building",
    },
    {
      id: "contact-3",
      name: "City Hospital",
      role: "Medical assistance",
      phone: "+919829011223",
      iconKey: "medical",
    },
    {
      id: "contact-4",
      name: "Police / Emergency",
      role: "Emergency services",
      phone: "112",
      iconKey: "shield",
    },
  ],
  backupHistory: [],
};
