import type { WorkspaceSnapshot } from "./types";

const categoryNames = [
  "Venue",
  "Catering",
  "Decoration",
  "Photography",
  "Bride",
  "Groom",
  "Jewellery",
  "Rituals",
  "Invitations",
  "Transport",
  "Accommodation",
  "Gifts",
  "Hidden Expenses",
  "Miscellaneous",
];

export const demoWorkspace: WorkspaceSnapshot = {
  version: 1,
  wedding: {
    id: "wedding-1",
    name: "Suman & Sumita",
    type: "Odia Hindu Wedding",
    date: "2026-12-14",
    location: "Berhampur, Odisha",
    currency: "INR",
  },
  events: [
    {
      id: "event-engagement",
      name: "Engagement",
      date: "2026-12-10",
      time: "18:30",
      location: "Berhampur, Odisha",
      notes: "Ring ceremony and family dinner.",
      sortOrder: 0,
    },
    {
      id: "event-haldi",
      name: "Haldi",
      date: "2026-12-12",
      time: "09:00",
      location: "Family home",
      notes: "Keep turmeric and floral jewellery ready.",
      sortOrder: 1,
    },
    {
      id: "event-mehendi",
      name: "Mehendi",
      date: "2026-12-12",
      time: "17:00",
      location: "Family home",
      sortOrder: 2,
    },
    {
      id: "event-wedding",
      name: "Wedding",
      date: "2026-12-14",
      time: "19:00",
      location: "Berhampur, Odisha",
      notes: "Bahaghara, Kanyadan and Saptapadi.",
      sortOrder: 3,
    },
    {
      id: "event-reception",
      name: "Reception",
      date: "2026-12-15",
      time: "19:00",
      location: "Berhampur, Odisha",
      sortOrder: 4,
    },
    {
      id: "event-gruhapravesh",
      name: "Gruhapravesh",
      date: "2026-12-16",
      time: "10:00",
      location: "Groom's home",
      sortOrder: 5,
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Confirm catering menu",
      eventId: "event-wedding",
      dueDate: "2026-10-20",
      priority: "High",
      status: "In Progress",
      responsiblePerson: "Suman",
    },
    {
      id: "task-2",
      title: "Collect invitation proof",
      eventId: "event-engagement",
      dueDate: "2026-10-10",
      priority: "Medium",
      status: "Not Started",
      responsiblePerson: "Sumita",
    },
    {
      id: "task-3",
      title: "Book bridal mehendi artist",
      eventId: "event-mehendi",
      dueDate: "2026-09-30",
      priority: "High",
      status: "Completed",
      responsiblePerson: "Sumita",
    },
  ],
  categories: categoryNames.map((name, sortOrder) => ({
    id: `category-${sortOrder + 1}`,
    name,
    sortOrder,
  })),
  expenses: [
    {
      id: "expense-1",
      title: "Wedding venue advance",
      categoryId: "category-1",
      estimatedPaise: 350000000,
      actualPaise: 300000000,
      paidPaise: 100000000,
      paymentStatus: "Partially Paid",
      vendorName: "Berhampur Convention Hall",
      dueDate: "2026-11-14",
    },
    {
      id: "expense-2",
      title: "Photography booking",
      categoryId: "category-4",
      estimatedPaise: 150000000,
      actualPaise: 150000000,
      paidPaise: 150000000,
      paymentStatus: "Paid",
      vendorName: "Frame Story Studios",
    },
    {
      id: "expense-3",
      title: "Catering estimate",
      categoryId: "category-2",
      estimatedPaise: 450000000,
      actualPaise: 0,
      paidPaise: 0,
      paymentStatus: "Not Paid",
      vendorName: "Annapurna Caterers",
      dueDate: "2026-12-07",
    },
  ],
};
